---
stages:
- name: CI-BUILD
  inputs:
  - type: git
    branch: develop
    service: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: Dev - Deploy
  inputs:
  - type: job
    stage: CI-BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: PIPELINE_IMAGE_URL
    value: gs-rest-service
    type: text
  jobs:
  - name: Test - WhiteBox
    type: tester
    target:
      region_id: ibm:yp:us-south
      organization: cesar.rodriguez.medina@ibm.com
      space: AICSpain
      application:
    WAIT_TIME: '5'
    script: "#!/bin/bash\necho -e \"Build environment variables:\"\necho \"REGISTRY_URL=${REGISTRY_URL}\"\
      \necho \"REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}\"\necho \"IMAGE_NAME=${IMAGE_NAME}\"\
      \necho \"BUILD_NUMBER=${BUILD_NUMBER}\"\n\n# Learn more about the available\
      \ environment variables at:\n# https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment\n\
      \n# To review or change build options use:\n# bx cr build --help\n\nls -la target/*.jar\n\
      jarToDeploy=$(ls target/*.jar)\necho -e \"Checking for Dockerfile at the repository\
      \ root\"\n#if [ -f Dockerfile ]; then \n#   echo \"Dockerfile found\"\n#else\n\
      echo \"Dockerfile not found. Creating it......\"\nDOCKERFILE_FILE=\"Dockerfile\"\
      \nDockerfile=$(cat <<EOF''\nFROM openjdk:8-jdk-alpine\nADD $jarToDeploy app.jar\n\
      EXPOSE 8080\nENTRYPOINT [\"java\",\"-Djava.security.egd=file:/dev/./urandom\"\
      ,\"-jar\",\"/app.jar\"]\nEOF\n)\n#fi\n\n# Replace the variables\necho \"$Dockerfile\"\
      \ > $DOCKERFILE_FILE\n\nsed -i 's|$jarToDeploy|'\"$jarToDeploy\"'|g' $DOCKERFILE_FILE\n\
      \necho \"cat $DOCKERFILE_FILE\"\ncat $DOCKERFILE_FILE\n\n\necho -e \"Building\
      \ container image\"\nset -x\nbx cr build -t $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER\
      \ .\nset +x\n"
